### ISSUE TITLE
Cobra Issue: running alongside Porcupine Angular creates `IO_ERROR`

### ISSUE THREAD

**Issue by sandeepsn1997** [Picovoice/cobra#109]
Cobra stops working when porcupine service in installed and used in angular 

getting this error

core.mjs:6494 ERROR Error: Uncaught (in promise): Error: 'pv_cobra_init' failed with status IO_ERROR
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25608:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)

when working with only cobra VAD it works fine, but once i installed porcupine service it stops working

**Comment by kenarsa** [comment]
thanks for the report. can you please share a repo that allows us to reproduce the issue and then we can work on it? it is ok if the repo is private.

**Comment by sandeepsn1997** [comment]
[cobra bug.zip](https://github.com/Picovoice/cobra/files/8834741/cobra.bug.zip)
I have zipped and shared the angular project.

**Comment by mrrostam** [comment]
@sandeepsn1997 Thank you for sharing the project, but I couldn't reproduce the issue described above as it only has Cobra and not Porcupine. Can you send me either another project with the problem you mentioned or a step-by-step guide on reproducing it with the one you already sent?

P.S: I deleted the link to the attached project since it has your `AccessKey` in plain text. Make sure to keep your AccessKey secret and removed from shared projects next time.

**Comment by mrrostam** [comment]
@sandeepsn1997 I was able to reproduce what you got by creating a dummy angular project, and released a hotfix for our Cobra web binding, could you please try version `1.1.7` and see if that solves the issue?

**Comment by sandeepsn1997** [comment]
Hello @mrrostam,

_I deleted the link to the attached project_  Thanks, I realised it after uploading🙂.
I did try 1.1.7 version and the issue is resolved. 
Thank you soo much for your quick response. 
Can't wait to build cool things using PicoVoice. 👍
