### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by Tryad0** [Picovoice/cobra#136]
Is there any doc for flutter or any implementation in progress? Would be awesome.

**Comment by laves** [comment]
Flutter is not supported at this time and isn't on our foreseeable roadmap. If you are an enterprise user, feel free to reach out to your Picovoice contact with this request. Otherwise, you can refer to our Flutter SDKs for [Porcupine](https://github.com/Picovoice/porcupine/tree/master/binding/flutter) and [Rhino](https://github.com/Picovoice/rhino/tree/master/binding/flutter) to see how you'd go about implementing a Native Plugin that supports this. We're always open to PRs from the community!
